model: abmil_custom      
data_dir: /data0/age_predict/preprocessed/coords/features_uni_v2
fold: 0
output_dir: ./experiments/abmil_custom_cond_sex_2

# Training parameters
batch_size: 4
num_epochs: 20
learning_rate: 1e-4
weight_decay: 1e-5
accumulation_steps: 1
num_tissues: 29

# W&B configuration
use_wandb: true
wandb_project: age-predict
wandb_entity: null 
wandb_name: abmil-cond-sex-uni
log_step: 100

# Model parameters
feature_extractor: uni
model_params:
  feature_dim: 1536
  head_dim: 256
  n_heads: 4
  gated: true
  tissue_embed: true
  sex_embed: true
  tissue_cond_mode: hypernetwork
  tissue_cond_embed_dim: 64
  
hydra:
  run:
    dir: experiments/log/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: experiments/log/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Dataset toggle
use_normal_data: false
